version: 2.1

orbs:
  android: circleci/android@2.2.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.04
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint